import * as THREE from 'three';

const assetPath = (path) => `${import.meta.env.BASE_URL}${path}`;

export const CONFIG = {
  models: {
    optimized: assetPath('models/peshka.optimized.glb'),
    fallback: assetPath('models/peshka.glb'),
    centerAndGround: true,
  },
  materials: {
    envMapIntensity: 0.3,
    renderEnvMapIntensity: 0.64,
    defaultMetalness: 0.05,
    minRoughness: 0.38,
    maxRoughness: 0.9,
    illustrated: {
      enabled: false,
      colorStrength: 0.18,
      flatShading: true,
    },
  },
  renderer: {
    exposure: 1.14,
    desktopPixelRatio: 1.75,
    mobilePixelRatio: 1.2,
  },
  scene: {
    background: 0x11151c,
    fogDensity: 0.02,
    cameraFov: 65,
    cameraNear: 0.15,
    cameraFar: 300,
    reflections: true,
  },
  reflections: {
    enabled: false,
    textureSize: 1024,
    maxMirrors: 4,
    minArea: 0.3,
    clipBias: 0.006,
    color: 0x9a8a78,
  },
  player: {
    height: 1.65,
    walkSpeed: 2.2,
    runSpeed: 4,
    lookSpeed: 0.0028,
    keyboardLookSpeed: 1.35,
    zoomFov: 42,
    zoomSpeed: 11,
    verticalSpeed: 1.4,
    minHeight: 0.75,
    maxHeight: 3.2,
    startPosition: new THREE.Vector3(0, 1.65, 2.7),
    collision: {
      enabled: true,
      stepHeight: 0.38,
      maxDrop: 4,
      gravity: 14,
      minGroundNormalY: 0.58,
      groundSnapSpeed: 14,
      probeInterval: 0.04,
    },
  },
  door: {
    nodeName: '',
    openAngle: -Math.PI / 2.05,
    interactionDistance: 3,
  },
  lighting: {
    defaultPreset: 'evening',
    modelPracticals: {
      materialName: /^Light_01$/i,
      color: 0xffb86f,
      intensity: 5.2,
      distance: 4.6,
      decay: 2,
      angle: Math.PI / 3.6,
      penumbra: 0.82,
      surfaceOffset: 0.04,
      targetDistance: 1.65,
      minSpacing: 0.9,
      maxLights: 18,
    },
    practicals: [
      { position: [-3, 2.25, 0], intensity: 0.62, distance: 4.8 },
      { position: [0, 2.25, 0], intensity: 0.72, distance: 4.8 },
      { position: [3, 2.25, 0], intensity: 0.62, distance: 4.8 },
      { position: [0, 1.65, 2.4], intensity: 0.1, distance: 2.8 },
    ],
    exterior: {
      position: [0, 2.8, 5.2],
      color: 0x6f86b7,
      intensity: 0.48,
      distance: 11,
    },
    presets: {
      evening: {
        label: 'French evening',
        background: 0x140f10,
        fogDensity: 0.018,
        hemisphere: { sky: 0x6d4c3f, ground: 0x2d1711, intensity: 0.34 },
        sun: { color: 0xffc27a, intensity: 0.12 },
        practicalIntensity: 1.14,
        exteriorIntensity: 0.55,
        environmentIntensity: 0.16,
        exposure: 1.04,
        bloom: 0.22,
      },
      day: {
        label: 'Day',
        background: 0xdfe8ef,
        fogDensity: 0.006,
        hemisphere: { sky: 0xcfe3ff, ground: 0x8c735e, intensity: 1.45 },
        sun: { color: 0xffe0b0, intensity: 2.4 },
        practicalIntensity: 0.16,
        exteriorIntensity: 0,
        environmentIntensity: 0.72,
        exposure: 1,
        bloom: 0.05,
      },
    },
  },
  postFX: {
    ssao: {
      enabled: true,
      mobileEnabled: false,
      kernelRadius: 14,
      minDistance: 0.004,
      maxDistance: 0.1,
    },
    bloom: {
      enabled: true,
      threshold: 0.88,
      strength: 0.2,
      radius: 0.36,
    },
    vignette: {
      enabled: true,
      darkness: 0.72,
      offset: 1.05,
    },
    illustration: {
      enabled: false,
      strength: 0.74,
      levels: 5,
      grain: 0.07,
      edgeStrength: 0.42,
      paperWarmth: 0.18,
      inkColor: 0x1c1715,
    },
  },
  visualPresets: {
    performance: {
      label: 'Performance',
      quality: 0.7,
      exposure: 1,
      ambient: 0.7,
      sun: 0.55,
      practical: 0.9,
      temperature: 2700,
      fog: 0.65,
      bloom: 0.12,
      bloomThreshold: 0.86,
      bloomRadius: 0.3,
      vignette: 0.54,
      illustration: 0,
      ssao: false,
      ssaoRadius: 8,
      ssaoMaxDistance: 0.07,
      shadows: false,
      shadowMapSize: 1024,
      modelShadowLights: 0,
      envMapIntensity: 0.22,
      status: 'Performance: warm evening mood with lighter rendering',
    },
    balanced: {
      label: 'French Bar',
      quality: 1,
      exposure: 1.04,
      ambient: 0.92,
      sun: 0.72,
      practical: 1.16,
      temperature: 2650,
      fog: 1,
      bloom: 0.24,
      bloomThreshold: 0.8,
      bloomRadius: 0.52,
      vignette: 0.68,
      illustration: 0,
      ssao: true,
      ssaoRadius: 16,
      ssaoMaxDistance: 0.11,
      shadows: true,
      shadowMapSize: 2048,
      modelShadowLights: 0,
      envMapIntensity: 0.3,
      status: 'French Bar preset: warm evening ambience for Peshka',
    },
    render: {
      label: 'Cinematic',
      quality: 1.45,
      exposure: 1.08,
      ambient: 0.98,
      sun: 0.64,
      practical: 1.48,
      temperature: 2450,
      fog: 1.08,
      bloom: 0.36,
      bloomThreshold: 0.72,
      bloomRadius: 0.68,
      vignette: 0.74,
      illustration: 0,
      ssao: true,
      ssaoRadius: 24,
      ssaoMaxDistance: 0.14,
      shadows: true,
      shadowMapSize: 4096,
      modelShadowLights: 6,
      envMapIntensity: 0.64,
      status: 'Cinematic preset: warm French evening bar atmosphere',
    },
  },
};
