import * as THREE from 'three';

const assetPath = (path) => `${import.meta.env.BASE_URL}${path}`;

export const CONFIG = {
  models: {
    optimized: assetPath('models/peshka.optimized.glb'),
    fallback: assetPath('models/peshka.glb'),
    centerAndGround: true,
  },
  materials: {
    envMapIntensity: 0.3,
    renderEnvMapIntensity: 0.64,
    defaultMetalness: 0.05,
    minRoughness: 0.38,
    maxRoughness: 0.9,
    colorBrightness: 1,
    illustrated: {
      enabled: false,
      colorStrength: 0.18,
      flatShading: true,
    },
  },
  renderer: {
    exposure: 1.14,
    desktopPixelRatio: 1.75,
    mobilePixelRatio: 1.2,
  },
  scene: {
    background: 0x11151c,
    fogDensity: 0.02,
    cameraFov: 65,
    cameraNear: 0.15,
    cameraFar: 300,
    reflections: true,
  },
  player: {
    height: 1.65,
    walkSpeed: 2.2,
    runSpeed: 4,
    lookSpeed: 0.0028,
    firstPersonInversion: { x: false, y: false },
    keyboardLookSpeed: 1.35,
    zoomFov: 42,
    zoomSpeed: 11,
    verticalSpeed: 1.4,
    jumpSpeed: 4.3,
    minHeight: 0.75,
    maxHeight: 3.2,
    startPosition: new THREE.Vector3(0, 1.65, 2.7),
    thirdPerson: {
      distance: 3.1,
      height: 0.68,
      targetOffset: -0.1,
      fov: 58,
      minDistance: 0.78,
      collisionOffset: 0.12,
      nearClipPadding: 0.18,
      inversion: { x: true, y: true },
    },
    collision: {
      enabled: true,
      stepHeight: 0.38,
      maxDrop: 4,
      gravity: 14,
      minGroundNormalY: 0.58,
      minCeilingNormalY: 0.55,
      ceilingProbeDistance: 1.2,
      headClearance: 0.14,
      groundSnapSpeed: 14,
      probeInterval: 0.04,
    },
  },
  lighting: {
    defaultPreset: 'evening',
    modelPracticals: {
      materialName: /^Light_01$/i,
      color: 0xffb86f,
      intensity: 5.2,
      distance: 4.6,
      decay: 2,
      angle: Math.PI / 3.6,
      penumbra: 0.82,
      surfaceOffset: 0.04,
      targetDistance: 1.65,
      minSpacing: 0.9,
      maxLights: 18,
    },
    practicals: [
      { position: [-3, 2.25, 0], intensity: 0.62, distance: 4.8 },
      { position: [0, 2.25, 0], intensity: 0.72, distance: 4.8 },
      { position: [3, 2.25, 0], intensity: 0.62, distance: 4.8 },
      { position: [0, 1.65, 2.4], intensity: 0.1, distance: 2.8 },
    ],
    exterior: {
      position: [0, 2.8, 5.2],
      color: 0x6f86b7,
      intensity: 0.48,
      distance: 11,
    },
    presets: {
      evening: {
        label: 'French evening',
        background: 0x140f10,
        fogDensity: 0.018,
        hemisphere: { sky: 0x6d4c3f, ground: 0x2d1711, intensity: 0.34 },
        sun: { color: 0xffc27a, intensity: 0.12 },
        practicalIntensity: 1.14,
        exteriorIntensity: 0.55,
        environmentIntensity: 0.16,
        exposure: 1.04,
        bloom: 0.22,
      },
    },
  },
  postFX: {
    ssao: {
      enabled: true,
      mobileEnabled: false,
      kernelRadius: 14,
      minDistance: 0.004,
      maxDistance: 0.1,
    },
    bloom: {
      enabled: true,
      threshold: 0.88,
      strength: 0.2,
      radius: 0.36,
    },
  },
  visualPresets: {
    balanced: {
      label: 'French Bar',
      quality: 1,
      exposure: 1.04,
      ambient: 1.34,
      sun: 0.74,
      practical: 1.14,
      temperature: 3000,
      fog: 0.74,
      bloom: 0.3,
      bloomThreshold: 0.95,
      bloomRadius: 0.52,
      ssao: true,
      ssaoRadius: 16,
      ssaoMaxDistance: 0.11,
      shadows: true,
      shadowMapSize: 2048,
      modelShadowLights: 0,
      envMapIntensity: 0.3,
      modelColorBrightness: 1.36,
      status: 'French Bar: saved warm evening presentation preset',
    },
  },
};
